version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/code      
    ports:
      - "5000:5000"
    env_file:
      .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_marshmallow

volumes:
  postgres_data: